version: '3.4'

services:
  consul-service:
    image: "hashicorp/consul:latest"
    command: consul agent -dev -log-level=warn -ui -client=0.0.0.0
    hostname: consul
    ports:
        - "8500:8500"
        - "8600:8600"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8500"]
        interval: 10s
        timeout: 5s
        retries: 5
  eureka-server:
    image:  springcloud/eureka
    hostname: eureka-server
    ports:
        - "8761:8761"
  swizlypeasy.clusters.demo:
    image: ${DOCKER_REGISTRY-}swizlypeasyclustersdemo
    build:
      context: .
      dockerfile: SwizlyPeasy.Clusters.Demo/Dockerfile
    depends_on:
      consul-service:
         condition: service_healthy
  swizlypeasy.clusters.demo.client1:
    image: ${DOCKER_REGISTRY-}swizlypeasydemoapi
    hostname: demo1
    ports:
        - "8002:80"
        - "8003:443"
    build:
        context: .
        dockerfile: SwizlyPeasy.Clusters.Demo.Client/Dockerfile
    depends_on:
        consul-service:
         condition: service_healthy
  swizlypeasy.clusters.demo.client2:
    image: ${DOCKER_REGISTRY-}swizlypeasydemoapi
    hostname: demo2
    ports:
        - "8004:80"
        - "8005:443"
    build:
        context: .
        dockerfile: SwizlyPeasy.Clusters.Demo.Client/Dockerfile
  swizlypeasy.clusters.demo.client3:
    image: ${DOCKER_REGISTRY-}swizlypeasydemoapi
    hostname: demo3
    ports:
        - "8006:80"
        - "8007:443"
    build:
        context: .
        dockerfile: SwizlyPeasy.Clusters.Demo.Client/Dockerfile 
    depends_on:
        consul-service:
         condition: service_healthy


